 
export default {
	languageOptions: {
		ecmaVersion: 2020,
		sourceType: 'module'
	},
	ignores: ['source/loading2/**'],
	rules: {
		'arrow-body-style': ['warn', 'always'],
		'arrow-parens': 'warn',
		'brace-style': ['warn', 'allman', {allowSingleLine: true}],
		camelcase: 'off',
		indent: ['warn', 'tab'],
		complexity: 'off',
		semi: ['warn', 'always'],
		'constructor-super': 'warn',
		curly: 'warn',
		eqeqeq: ['warn', 'smart'],
		'guard-for-in': 'off',
		'id-blacklist': 'off',
		'id-match': 'off',
		// 'sort-imports': ['off', {
		// 	ignoreCase: false,
		// 	ignoreDeclarationSort: false,
		// 	ignoreMemberSort: false,
		// 	memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single']
		// }],
		// 'import/no-deprecated': 'off',
		// 'import/no-unassigned-import': 'off',
		// 'import/order': 'error',
		// 'jsdoc/check-alignment': 'error',
		// 'jsdoc/check-indentation': 'off',
		// 'jsdoc/newline-after-description': 'error',
		// 'jsdoc/no-types': 'off',
		'max-classes-per-file': 'off',
		'max-len': 'off',
		'lines-between-class-members': 'warn',
		'space-before-blocks': ['warn', 'always'],
		'no-multi-spaces': 'warn',
		'keyword-spacing': ['warn', {after: true, before: true}],
		'new-parens': 'warn',
		'no-bitwise': 'off',
		'no-caller': 'warn',
		'no-cond-assign': 'warn',
		'no-console': 'off',
		'no-debugger': 'off',
		'no-duplicate-imports': 'warn',
		'no-empty': 'off',
		'no-eval': 'off',
		'no-fallthrough': 'warn',
		'no-invalid-this': 'off',
		'no-multiple-empty-lines': 'warn',
		'no-new-wrappers': 'warn',
		'no-redeclare': 'off',
		'no-shadow': 'off',
		'no-restricted-imports': 'warn',
		'no-sequences': 'warn',
		'no-sparse-arrays': 'warn',
		'no-throw-literal': 'warn',
		'no-trailing-spaces': 'off',
		'no-undef-init': 'warn',
		'no-underscore-dangle': 'off',
		'no-unsafe-finally': 'warn',
		'no-unused-labels': 'warn',
		'no-dupe-args': 'warn',
		'no-dupe-keys': 'warn',
		'no-dupe-else-if': 'warn',
		'no-duplicate-case': 'warn',
		'no-invalid-regexp': 'warn',
		'no-inner-declarations': 'off',
		'no-with': 'warn',
		'no-useless-catch': 'warn',
		'no-setter-return': 'warn',
		'no-unexpected-multiline': 'warn',
		'no-unreachable': 'warn',
		'no-irregular-whitespace': 'warn',
		'no-implicit-coercion': 'warn',
		'no-var': 'off',
		'no-extra-parens': 'warn',
		'arrow-spacing': 'warn',
		'object-shorthand': ['warn', 'never'],
		'one-var': ['off', 'never'],
		'prefer-arrow/prefer-arrow-functions': 'off',
		'prefer-const': 'warn',
		'prefer-object-spread': 'off',
		'rest-spread-spacing': ['warn', 'never'],
		'no-useless-call': 'warn',
		'quote-props': 'off',
		quotes: ['warn', 'single'],
		radix: 'off',
		'use-isnan': 'warn',
		'valid-typeof': 'warn',
		'spaced-comment': [
			'warn',
			'always',
			{markers: ['/']}
		],
		'capitalized-comments': 'off',
		'eol-last': ['warn', 'always'],
		'no-unneeded-ternary': 'warn',
		'object-curly-newline': ['warn', {multiline: true}],
		'object-property-newline': ['warn', {allowAllPropertiesOnSameLine: true}],
		'object-curly-spacing': ['warn', 'never'],
		'array-bracket-spacing': ['warn', 'never'],
		'space-before-function-paren': ['warn', 'never'],
		'computed-property-spacing': ['warn', 'never'],
		'comma-spacing': ['warn', {'before': false, 'after': true}],
		'key-spacing': ['warn', {'beforeColon': false, 'afterColon': true}],
		'comma-dangle': ['warn', 'never']
	}
};
